id: P004375
initial_creation_type: ocr
source_metadata:
  id: bdr:W23390
  title: གཅོད་ཚོགས་ཀྱི་ལག་ལེན་སོགས
  author: ''
  volumes:
    9b4f9f8f351f48a0849900daba729786:
      image_group_id: I1567
      title: ''
      volume_number: 1
      total_pages: 556
