id: I4424E880
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:17:18+00:00'
last_modified: '2022-06-07T22:24:32.064881+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23390
  title: གཅོད་ཚོགས་ཀྱི་ལག་ལེན་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0990:
      image_group_id: I1567
      title: ''
      total_pages: 556
      order: 1
      base_file: 0990.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
